// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNrjGwhhkAmqV8y54JVEgfi_CmounnKSI',
    appId: '1:303034471793:web:0a2ca14fa8f71ee14f52d0',
    messagingSenderId: '303034471793',
    projectId: 'pick-up-platform-prototype',
    authDomain: 'pick-up-platform-prototype.firebaseapp.com',
    databaseURL: 'https://pick-up-platform-prototype-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pick-up-platform-prototype.firebasestorage.app',
    measurementId: 'G-4D848C47YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxV1sMLN4pI4CQ7LPG17HSSRifnoh9SA',
    appId: '1:303034471793:android:64ba6e4b7ab393d24f52d0',
    messagingSenderId: '303034471793',
    projectId: 'pick-up-platform-prototype',
    databaseURL: 'https://pick-up-platform-prototype-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pick-up-platform-prototype.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD58uuO_cjqyZZ8uA94ql-Slf791G_pVQM',
    appId: '1:303034471793:ios:9366213e6ad833944f52d0',
    messagingSenderId: '303034471793',
    projectId: 'pick-up-platform-prototype',
    databaseURL: 'https://pick-up-platform-prototype-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pick-up-platform-prototype.firebasestorage.app',
    iosBundleId: 'com.example.liveOrderApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD58uuO_cjqyZZ8uA94ql-Slf791G_pVQM',
    appId: '1:303034471793:ios:9366213e6ad833944f52d0',
    messagingSenderId: '303034471793',
    projectId: 'pick-up-platform-prototype',
    databaseURL: 'https://pick-up-platform-prototype-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pick-up-platform-prototype.firebasestorage.app',
    iosBundleId: 'com.example.liveOrderApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNrjGwhhkAmqV8y54JVEgfi_CmounnKSI',
    appId: '1:303034471793:web:14a59e9dda4f2d6d4f52d0',
    messagingSenderId: '303034471793',
    projectId: 'pick-up-platform-prototype',
    authDomain: 'pick-up-platform-prototype.firebaseapp.com',
    databaseURL: 'https://pick-up-platform-prototype-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pick-up-platform-prototype.firebasestorage.app',
    measurementId: 'G-7RQWVQKCVJ',
  );
}
